
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores4;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR2 = 14;
  public static final int DOSPUNTOS = 20;
  public static final int PAR1 = 13;
  public static final int CONST = 34;
  public static final int POR = 4;
  public static final int PUNTOYCOMA = 19;
  public static final int LLAVE2 = 22;
  public static final int LLAVE1 = 21;
  public static final int CASE = 44;
  public static final int COMENTARIOS = 26;
  public static final int PORCENTAJE = 31;
  public static final int FOR = 38;
  public static final int LETRAS = 9;
  public static final int CADENAS = 12;
  public static final int NOT = 18;
  public static final int AND = 29;
  public static final int IGUAL = 17;
  public static final int LETRAS2 = 10;
  public static final int DIVIDIDO = 5;
  public static final int OR = 30;
  public static final int CLASS = 37;
  public static final int IF = 35;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMILLA = 25;
  public static final int COMA = 23;
  public static final int MENOS = 3;
  public static final int MENOR = 15;
  public static final int REQUIRE = 46;
  public static final int COMENINICIAL = 27;
  public static final int BREAK = 42;
  public static final int ENTEROS = 6;
  public static final int DECIMALES = 8;
  public static final int SWITCH = 41;
  public static final int MAYOR = 16;
  public static final int ELSE = 36;
  public static final int COMBINACION = 11;
  public static final int PUNTO = 24;
  public static final int WHILE = 39;
  public static final int DEFAULT = 43;
  public static final int COMENFINAL = 28;
  public static final int LET = 33;
  public static final int VAR = 32;
  public static final int ENTEROS2 = 7;
  public static final int CONSOLE = 45;
  public static final int DO = 40;
  public static final int MAS = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "ENTEROS",
  "ENTEROS2",
  "DECIMALES",
  "LETRAS",
  "LETRAS2",
  "COMBINACION",
  "CADENAS",
  "PAR1",
  "PAR2",
  "MENOR",
  "MAYOR",
  "IGUAL",
  "NOT",
  "PUNTOYCOMA",
  "DOSPUNTOS",
  "LLAVE1",
  "LLAVE2",
  "COMA",
  "PUNTO",
  "COMILLA",
  "COMENTARIOS",
  "COMENINICIAL",
  "COMENFINAL",
  "AND",
  "OR",
  "PORCENTAJE",
  "VAR",
  "LET",
  "CONST",
  "IF",
  "ELSE",
  "CLASS",
  "FOR",
  "WHILE",
  "DO",
  "SWITCH",
  "BREAK",
  "DEFAULT",
  "CASE",
  "CONSOLE",
  "REQUIRE"
  };
}

