
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores3;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR2 = 11;
  public static final int DOSPUNTOS = 16;
  public static final int PAR1 = 10;
  public static final int PUNTOYCOMA = 15;
  public static final int LLAVE2 = 18;
  public static final int LLAVE1 = 17;
  public static final int GRAFICAPIE = 31;
  public static final int DOUBLE = 27;
  public static final int COMENTARIOS = 21;
  public static final int CDM = 13;
  public static final int LETRAS = 7;
  public static final int TITULOY = 37;
  public static final int TITULOX = 36;
  public static final int MONEDA = 24;
  public static final int CADENAS = 9;
  public static final int EJEX = 38;
  public static final int IGUAL = 12;
  public static final int ARCHIVO = 40;
  public static final int PUNTAJEGENERAL = 34;
  public static final int DIVIDIDO = 14;
  public static final int CORCHETE2 = 3;
  public static final int CORCHETE1 = 2;
  public static final int TITULO = 35;
  public static final int DEFINIRGLOBALES = 28;
  public static final int EOF = 0;
  public static final int VALORES = 39;
  public static final int error = 1;
  public static final int COMILLA = 20;
  public static final int COMA = 19;
  public static final int GRAFICALINEAS = 32;
  public static final int COMENINICIAL = 22;
  public static final int PUNTAJEESPECIFICO = 33;
  public static final int ENTEROS = 4;
  public static final int DECIMALES = 6;
  public static final int COMPARE = 25;
  public static final int GENERARREPORTEESTADISTICO = 29;
  public static final int COMBINACION = 8;
  public static final int GRAFICABARRAS = 30;
  public static final int COMENFINAL = 23;
  public static final int STRING = 26;
  public static final int OTROENTERO = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CORCHETE1",
  "CORCHETE2",
  "ENTEROS",
  "OTROENTERO",
  "DECIMALES",
  "LETRAS",
  "COMBINACION",
  "CADENAS",
  "PAR1",
  "PAR2",
  "IGUAL",
  "CDM",
  "DIVIDIDO",
  "PUNTOYCOMA",
  "DOSPUNTOS",
  "LLAVE1",
  "LLAVE2",
  "COMA",
  "COMILLA",
  "COMENTARIOS",
  "COMENINICIAL",
  "COMENFINAL",
  "MONEDA",
  "COMPARE",
  "STRING",
  "DOUBLE",
  "DEFINIRGLOBALES",
  "GENERARREPORTEESTADISTICO",
  "GRAFICABARRAS",
  "GRAFICAPIE",
  "GRAFICALINEAS",
  "PUNTAJEESPECIFICO",
  "PUNTAJEGENERAL",
  "TITULO",
  "TITULOX",
  "TITULOY",
  "EJEX",
  "VALORES",
  "ARCHIVO"
  };
}

